- name: Update apt cache
  apt:
    update_cache: yes
  tags: 
    - update-packges

- name: Install additional packages
  apt:
    name: "{{ additional_packages }}"
    state: present
  tags: 
    - update-packges