- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload Nginx

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/static-images
  notify:
    - Reload Nginx
  tags: 
    - update-nginx-rule

- name: Ensure Nginx is running
  shell: |
    if ! pgrep nginx; then
      nginx;
    else
      echo "Nginx is already running"
    fi